### PR TITLE
Add PLEP 5 on versioning and releases

### PR DESCRIPTION
**Pull request by namurphy**
The purpose of this PlasmaPy Enrichment Proposal is to specify the versioning scheme to be used for PlasmaPy (for during development, prior to releases, and final releases), and the schedule for releases (no less frequently than once every six months).

### CODE REVIEW

**Comment by namurphy** [comment]
@Cadair - Since I'm basing much of this PLEP on https://github.com/sunpy/sunpy-SEP/pull/30, would you like to be a co-author?  Alternatively, would you be willing to release https://github.com/sunpy/sunpy-SEP/pull/30 under CC BY 4.0?

**Comment by Cadair** [comment]
@namurphy I am happy to be co-author. I also got around to merging the licence for the SEP repo: https://github.com/sunpy/sunpy-SEP/blob/master/LICENSE.md

**Comment by SolarDrew** [comment]
👍

**Comment by Cadair** [comment]
Just to let you know, there has been a *lot* of discussion on sunpy/sunpy-SEP#30 about this, to the point where we are now probably going to take a slightly different approach. I would recommend you have a read over it all and consider how the arguments made there affect you.

**Comment by namurphy** [comment]
Coordinating Committee members - please vote on PLEP 5! Any additional suggestions from the community are still appreciated.

I vote in favor. slightly_smiling_face +1

(Also, during today's telecon we noted the discussion at https://github.com/sunpy/sunpy-SEP/pull/30 with potential problems with using semantic versioning.  If problems with semantic versioning do arise later on, we can still amend this PLEP to change the versioning scheme.)

**Comment by tulasinandan** [comment]
In favor! :+1:

**Comment by namurphy** [comment]
@StanczakDominik and @SolarDrew - Would either of you have a chance to vote on this soon?

**Comment by StanczakDominik** [comment]
Oh, I thought I had done that, sorry. I vote yup.

**Comment by SolarDrew** [comment]
:+1:

**Pull request merged**
